version: '3'
services:
  api:
    container_name: ladder-hero-api
    image: jhonnold/ladder-hero-api:dev
    ports:
    - 8080:8080
    logging:
      driver: json-file
    environment:
      SPRING_PROFILES_ACTIVE: prod
      R2DBC_CONNECTION_STRING: ${R2DBC_CONNECTION_STRING}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JDBC_CONNECTION_STRING: ${JDBC_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      BLIZZARD_CLIENT_ID: ${BLIZZARD_CLIENT_ID}
