spring:
  r2dbc:
    url: ${R2DBC_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    max-size: 64

  flyway:
    url: ${JDBC_CONNECTION_STRING}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    platform: postgres

admin:
  user: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}

aws:
  s3:
    region: us-east-2
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}

logging:
  level:
    root: INFO
    me:
      honnold: DEBUG